import { auth, db } from "./firebase-config.js";

import {
  onAuthStateChanged,
  signOut
} from "https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js";

import {
  doc,
  getDoc,
  collection,
  getDocs
} from "https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js";

/*
  MauMarket nav.js
  Private-merchant shared navigation
  - Product-first buyer navigation
  - No public shop or seller-directory links
  - Dynamic categories from Firestore
  - Role-based account menus
  - Instant marketplace search
  - Sticky desktop navigation
  - Mobile side menu and bottom navigation
  - Firestore cart badge
*/

const LOGO_PATH = "images/maumarketlogo.png";

/*
  Logo sizing is handled here because the shared navbar is generated by nav.js.
  This keeps the MauMarket logo visible without changing every HTML page.
*/
const NAV_LOGO_DESKTOP_WIDTH = "190px";
const NAV_LOGO_DESKTOP_HEIGHT = "74px";
const NAV_LOGO_MOBILE_WIDTH = "132px";
const NAV_LOGO_MOBILE_HEIGHT = "58px";

let currentUser = null;
let currentRole = "guest";
let userData = null;

let navCategories = [];

document.addEventListener("DOMContentLoaded", async () => {
  buildResponsiveNav();
  await loadNavCategories();

  onAuthStateChanged(auth, async (user) => {
    currentUser = user;
    currentRole = "guest";
    userData = null;

    if (user) {
      try {
        const userSnap = await getDoc(doc(db, "users", user.uid));

        if (userSnap.exists()) {
          userData = userSnap.data();
          currentRole = userData.role || "customer";
        } else {
          currentRole = "customer";
        }
      } catch (error) {
        console.warn("Could not load navigation account information.");
        currentRole = "customer";
      }
    }

    renderNavLinks();
    await updateCartBadge();
  });
});

function buildResponsiveNav() {
  removeInjectedNavigation();
  removeOldHeaders();
  injectNavLogoStyles();

  const header = document.createElement("header");
  header.id = "mmSharedNav";
  header.className = "mm-nav premium-mm-nav";

  header.innerHTML = `
    <div class="mm-nav-inner">
      <button id="mmMenuBtn" class="mm-icon-btn premium-menu-btn" type="button" aria-label="Open menu" aria-expanded="false" aria-controls="mmSideMenu">
        <span></span>
        <span></span>
        <span></span>
      </button>

      <a href="index.html" class="mm-logo mm-brand-logo" aria-label="MauMarket home">
        <img src="${LOGO_PATH}" alt="MauMarket" class="mm-brand-logo-img" decoding="async">
      </a>

      <form id="mmSearchForm" class="mm-search premium-search">
        <select id="mmSearchCategory" aria-label="Category">
          <option value="">Loading Categories...</option>
        </select>

        <input id="mmSearchInput" type="search" placeholder="Search products and services..." autocomplete="off">

        <button type="submit" aria-label="Search">Search</button>
      </form>

      <nav id="mmDesktopLinks" class="mm-desktop-links"></nav>

      <a href="cart.html" class="mm-cart-btn" aria-label="Cart">
        <span id="mmCartBadge" class="mm-cart-badge">0</span>
        <svg class="cart-icon" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
          <path d="M3 5H5L7.2 15.2C7.32 15.72 7.78 16.1 8.32 16.1H18.2C18.72 16.1 19.18 15.75 19.32 15.25L21 8H6" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
          <circle cx="9" cy="20" r="1.6" fill="currentColor"/>
          <circle cx="18" cy="20" r="1.6" fill="currentColor"/>
        </svg>
      </a>
    </div>
  `;

  document.body.prepend(header);

  const mobileSearch = document.createElement("section");
  mobileSearch.id = "mmMobileSearch";
  mobileSearch.className = "mm-mobile-search-wrap";
  mobileSearch.innerHTML = `
    <form id="mmMobileSearchForm" class="mm-mobile-search">
      <input id="mmMobileSearchInput" type="search" placeholder="Search products and services..." autocomplete="off">
      <button type="submit" aria-label="Search">⌕</button>
    </form>
  `;

  header.insertAdjacentElement("afterend", mobileSearch);

  const overlay = document.createElement("div");
  overlay.id = "mmMenuOverlay";
  overlay.className = "mm-menu-overlay";
  overlay.setAttribute("aria-hidden", "true");

  const sideMenu = document.createElement("aside");
  sideMenu.id = "mmSideMenu";
  sideMenu.className = "mm-side-menu premium-side-menu";
  sideMenu.setAttribute("aria-hidden", "true");
  sideMenu.inert = true;

  sideMenu.innerHTML = `
    <div class="mm-side-head">
      <a href="index.html" class="mm-side-logo" aria-label="MauMarket home">
        <img src="${LOGO_PATH}" alt="MauMarket" decoding="async">
      </a>
      <button id="mmMenuClose" class="mm-side-close" type="button" aria-label="Close menu">×</button>
    </div>

    <div id="mmUserBox" class="mm-user-box">
      Loading...
    </div>

    <nav id="mmMobileLinks" class="mm-mobile-links"></nav>
  `;

  const bottomNav = document.createElement("nav");
  bottomNav.id = "mmBottomNav";
  bottomNav.className = "mm-bottom-nav";

  document.body.appendChild(overlay);
  document.body.appendChild(sideMenu);
  document.body.appendChild(bottomNav);

  /*
    Always reset the drawer to its closed state after injection.
    This prevents stale browser state or old CSS rules from showing
    the side-menu logo as a large banner over the page.
  */
  closeMenu({ restoreFocus: false });

  document.getElementById("mmMenuBtn")?.addEventListener("click", toggleMenu);
  document.getElementById("mmMenuClose")?.addEventListener("click", closeMenu);
  overlay.addEventListener("click", closeMenu);

  document.addEventListener("keydown", (event) => {
    if (event.key === "Escape") closeMenu();
  });

  document.getElementById("mmSearchForm")?.addEventListener("submit", (event) => {
    event.preventDefault();
    runNavSearch(true);
  });

  document.getElementById("mmSearchInput")?.addEventListener("input", () => {
    if (isProductsPage()) {
      runNavSearch(false);
    }
  });

  document.getElementById("mmSearchCategory")?.addEventListener("change", () => {
    if (isProductsPage()) {
      runNavSearch(true);
    }
  });

  document.getElementById("mmMobileSearchForm")?.addEventListener("submit", (event) => {
    event.preventDefault();
    runMobileNavSearch(true);
  });

  document.getElementById("mmMobileSearchInput")?.addEventListener("input", () => {
    if (isProductsPage()) {
      runMobileNavSearch(false);
    }
  });
}



async function loadNavCategories() {
  const categorySelect = document.getElementById("mmSearchCategory");

  if (!categorySelect) return;

  categorySelect.disabled = true;
  categorySelect.innerHTML = `<option value="">Loading Categories...</option>`;

  try {
    const snapshot = await getDocs(collection(db, "categories"));

    navCategories = [];

    snapshot.forEach((docSnap) => {
      const category = {
        id: docSnap.id,
        ...docSnap.data()
      };

      if (category.active !== false && category.name) {
        navCategories.push(category);
      }
    });

    navCategories.sort((a, b) => {
      const aOrder = Number(a.sortOrder || 0);
      const bOrder = Number(b.sortOrder || 0);

      if (aOrder !== bOrder) return aOrder - bOrder;

      return String(a.name || "").localeCompare(String(b.name || ""));
    });

    renderNavCategoryOptions();
  } catch (error) {
    console.warn("Could not load navigation categories.");
    renderNavCategoryFallback();
  }

  categorySelect.disabled = false;
}

function renderNavCategoryOptions() {
  const categorySelect = document.getElementById("mmSearchCategory");

  if (!categorySelect) return;

  const params = new URLSearchParams(window.location.search);
  const selectedCategory = params.get("category") || "";

  categorySelect.innerHTML = `<option value="">All Categories</option>`;

  navCategories.forEach((category) => {
    const option = document.createElement("option");

    option.value = category.name;
    option.textContent = category.name;

    categorySelect.appendChild(option);
  });

  if (selectedCategory) {
    ensureNavCategoryOption(selectedCategory);
    categorySelect.value = selectedCategory;
  }
}

function renderNavCategoryFallback() {
  navCategories = [
    { name: "Other", sortOrder: 999 }
  ];

  renderNavCategoryOptions();
}

function ensureNavCategoryOption(categoryName) {
  const categorySelect = document.getElementById("mmSearchCategory");

  if (!categorySelect || !categoryName) return;

  const exists = Array.from(categorySelect.options).some(
    (option) => option.value === categoryName
  );

  if (!exists) {
    const option = document.createElement("option");

    option.value = categoryName;
    option.textContent = `${categoryName} (Existing category)`;

    categorySelect.appendChild(option);
  }
}

function injectNavLogoStyles() {
  document
    .getElementById("maumarket-nav-logo-size-fix")
    ?.remove();

  const style = document.createElement("style");
  style.id = "maumarket-nav-logo-size-fix";

  style.textContent = `
    /* Main navigation must remain part of the page flow. */
    #mmSharedNav.mm-nav {
      position: relative !important;
      top: auto !important;
      width: 100% !important;
      z-index: 5000 !important;
    }

    #mmSharedNav .mm-logo.mm-brand-logo {
      width: ${NAV_LOGO_DESKTOP_WIDTH} !important;
      min-width: ${NAV_LOGO_DESKTOP_WIDTH} !important;
      height: ${NAV_LOGO_DESKTOP_HEIGHT} !important;
      display: flex !important;
      align-items: center !important;
      justify-content: flex-start !important;
      overflow: hidden !important;
      flex-shrink: 0 !important;
    }

    #mmSharedNav .mm-logo.mm-brand-logo img,
    #mmSharedNav .mm-brand-logo-img {
      width: ${NAV_LOGO_DESKTOP_WIDTH} !important;
      height: ${NAV_LOGO_DESKTOP_HEIGHT} !important;
      max-width: 100% !important;
      max-height: ${NAV_LOGO_DESKTOP_HEIGHT} !important;
      object-fit: contain !important;
      object-position: left center !important;
      display: block !important;
      transform: none !important;
    }

    /* Overlay stays mounted but invisible until the menu is opened. */
    #mmMenuOverlay.mm-menu-overlay {
      display: block !important;
      position: fixed !important;
      inset: 0 !important;
      z-index: 10001 !important;
      background: rgba(7, 11, 40, 0.62) !important;
      backdrop-filter: blur(4px);
      visibility: hidden !important;
      opacity: 0 !important;
      pointer-events: none !important;
      transition:
        opacity 0.2s ease,
        visibility 0.2s ease !important;
    }

    #mmMenuOverlay.mm-menu-overlay.show {
      visibility: visible !important;
      opacity: 1 !important;
      pointer-events: auto !important;
    }

    /*
      The drawer uses transform rather than the old left property.
      This guarantees the whole logo/header stays outside the viewport
      until the hamburger is pressed.
    */
    #mmSideMenu.mm-side-menu {
      display: block !important;
      position: fixed !important;
      top: 0 !important;
      left: 0 !important;
      width: min(360px, 88vw) !important;
      max-width: 88vw !important;
      height: 100dvh !important;
      min-height: 100vh !important;
      padding: 20px !important;
      overflow-x: hidden !important;
      overflow-y: auto !important;
      background: #ffffff !important;
      color: #0f172a !important;
      z-index: 10002 !important;
      box-shadow: 30px 0 80px rgba(7, 11, 40, 0.28) !important;
      transform: translateX(-110%) !important;
      visibility: hidden !important;
      opacity: 0 !important;
      pointer-events: none !important;
      transition:
        transform 0.25s ease,
        opacity 0.2s ease,
        visibility 0.2s ease !important;
    }

    #mmSideMenu.mm-side-menu.show {
      transform: translateX(0) !important;
      visibility: visible !important;
      opacity: 1 !important;
      pointer-events: auto !important;
    }

    #mmSideMenu .mm-side-head {
      width: 100% !important;
      display: flex !important;
      align-items: center !important;
      justify-content: space-between !important;
      gap: 12px !important;
      margin: 0 0 18px !important;
      padding: 0 0 16px !important;
      border-bottom: 1px solid #e6e8f0 !important;
      background: transparent !important;
    }

    #mmSideMenu .mm-side-logo {
      width: min(210px, calc(100% - 58px)) !important;
      max-width: calc(100% - 58px) !important;
      height: 62px !important;
      display: flex !important;
      align-items: center !important;
      overflow: hidden !important;
    }

    #mmSideMenu .mm-side-logo img {
      width: 100% !important;
      height: 62px !important;
      max-width: 100% !important;
      max-height: 62px !important;
      object-fit: contain !important;
      object-position: left center !important;
      transform: none !important;
    }

    #mmSideMenu .mm-side-close {
      position: static !important;
      width: 44px !important;
      height: 44px !important;
      min-width: 44px !important;
      min-height: 44px !important;
      margin: 0 !important;
      padding: 0 !important;
      border-radius: 50% !important;
      background: linear-gradient(135deg, #4f35f5, #7557ff) !important;
      color: #ffffff !important;
      font-size: 21px !important;
      line-height: 1 !important;
      box-shadow: 0 10px 24px rgba(79, 53, 245, 0.25) !important;
    }

    #mmMobileSearch.mm-mobile-search-wrap {
      width: min(1500px, 94%) !important;
      margin: 12px auto 8px !important;
      padding: 0 !important;
    }

    #mmMobileSearch .mm-mobile-search {
      width: 100% !important;
      min-height: 58px !important;
      display: grid !important;
      grid-template-columns: minmax(0, 1fr) 70px !important;
      margin: 0 !important;
      padding: 0 !important;
      overflow: hidden !important;
      border: 1px solid #e3e0f8 !important;
      border-radius: 20px !important;
      background: #ffffff !important;
      box-shadow: 0 10px 24px rgba(15, 23, 42, 0.08) !important;
    }

    #mmMobileSearch .mm-mobile-search input,
    #mmMobileSearch .mm-mobile-search button {
      height: 58px !important;
      min-height: 58px !important;
      margin: 0 !important;
      border: 0 !important;
      border-radius: 0 !important;
      box-shadow: none !important;
    }

    #mmMobileSearch .mm-mobile-search input {
      padding: 0 17px !important;
      font-size: 16px !important;
    }

    #mmMobileSearch .mm-mobile-search button {
      width: 70px !important;
      padding: 0 !important;
      background: linear-gradient(135deg, #4f35f5, #7557ff) !important;
      color: #ffffff !important;
      font-size: 23px !important;
    }

    @media (min-width: 981px) {
      #mmMobileSearch {
        display: none !important;
      }
    }

    @media (max-width: 980px) {
      #mmSharedNav .mm-nav-inner {
        width: 100% !important;
        min-height: 104px !important;
        display: grid !important;
        grid-template-columns: 58px minmax(0, 1fr) 58px !important;
        grid-template-areas: "menu logo cart" !important;
        align-items: center !important;
        gap: 10px !important;
        margin: 0 !important;
        padding: 13px 14px !important;
        border-radius: 0 !important;
      }

      #mmSharedNav .mm-icon-btn {
        grid-area: menu !important;
      }

      #mmSharedNav .mm-logo.mm-brand-logo {
        grid-area: logo !important;
        width: 100% !important;
        min-width: 0 !important;
        height: ${NAV_LOGO_MOBILE_HEIGHT} !important;
        margin: 0 auto !important;
        justify-content: center !important;
      }

      #mmSharedNav .mm-logo.mm-brand-logo img,
      #mmSharedNav .mm-brand-logo-img {
        width: min(235px, 100%) !important;
        height: ${NAV_LOGO_MOBILE_HEIGHT} !important;
        max-width: 100% !important;
        max-height: ${NAV_LOGO_MOBILE_HEIGHT} !important;
        object-position: center !important;
      }

      #mmSharedNav .mm-cart-btn {
        grid-area: cart !important;
      }

      #mmSharedNav .mm-icon-btn,
      #mmSharedNav .mm-cart-btn {
        width: 54px !important;
        height: 54px !important;
        min-height: 54px !important;
        margin: 0 !important;
        padding: 0 !important;
        border-radius: 18px !important;
      }

      #mmSharedNav .mm-search,
      #mmSharedNav .mm-desktop-links {
        display: none !important;
      }

      #mmMobileSearch.mm-mobile-search-wrap {
        display: block !important;
        width: calc(100% - 24px) !important;
      }
    }

    @media (max-width: 420px) {
      #mmSharedNav .mm-nav-inner {
        min-height: 98px !important;
        grid-template-columns: 54px minmax(0, 1fr) 54px !important;
        padding: 12px !important;
      }

      #mmSharedNav .mm-logo.mm-brand-logo {
        height: 54px !important;
      }

      #mmSharedNav .mm-logo.mm-brand-logo img,
      #mmSharedNav .mm-brand-logo-img {
        width: min(205px, 100%) !important;
        height: 54px !important;
        max-height: 54px !important;
      }

      #mmSharedNav .mm-icon-btn,
      #mmSharedNav .mm-cart-btn {
        width: 50px !important;
        height: 50px !important;
        min-height: 50px !important;
      }
    }
  `;

  document.head.appendChild(style);
}


function removeInjectedNavigation() {
  [
    "#mmSharedNav",
    "#mmMobileSearch",
    "#mmMenuOverlay",
    "#mmSideMenu",
    "#mmBottomNav"
  ].forEach((selector) => {
    document.querySelector(selector)?.remove();
  });

  document.body.classList.remove("menu-open");
}

function removeOldHeaders() {
  const selectors = [
    ".mobile-market-header",
    ".mobile-search-area",
    ".mobile-side-menu",
    ".mobile-menu-overlay",
    ".market-pro-header",
    ".amazon-topbar",
    ".amazon-subnav",
    ".navbar",
    ".market-mobile-header"
  ];

  selectors.forEach((selector) => {
    document.querySelectorAll(selector).forEach((element) => {
      element.style.display = "none";
    });
  });
}

function renderNavLinks() {
  const desktopLinks = document.getElementById("mmDesktopLinks");
  const mobileLinks = document.getElementById("mmMobileLinks");
  const userBox = document.getElementById("mmUserBox");
  const bottomNav = document.getElementById("mmBottomNav");

  if (!desktopLinks || !mobileLinks || !userBox || !bottomNav) return;

  const links = getLinksForRole();
  const desktop = links.filter((link) => link.desktop !== false);

  desktopLinks.innerHTML = desktop
    .map((link) => renderDesktopLink(link))
    .join("");

  mobileLinks.innerHTML = links
    .map((link) => renderMobileLink(link))
    .join("");

  bottomNav.innerHTML = getBottomLinks()
    .map((link) => renderBottomLink(link))
    .join("");

  userBox.innerHTML = getUserBoxHtml();

  document.querySelectorAll("[data-action='logout']").forEach((button) => {
    button.addEventListener("click", logoutUser);
  });

  document.querySelectorAll(".mm-mobile-link, .mm-bottom-link").forEach((link) => {
    link.addEventListener("click", () => {
      if (!link.dataset.action) closeMenu();
    });
  });

  markCurrentLinks();
}

function renderDesktopLink(link) {
  if (link.isButton) {
    return `
      <button class="mm-link-button" data-action="${escapeHtml(link.action)}" type="button">
        ${escapeHtml(link.label)}
      </button>
    `;
  }

  return `
    <a href="${escapeHtml(link.href)}" aria-label="${escapeHtml(link.label)}">
      ${escapeHtml(link.label)}
    </a>
  `;
}

function renderMobileLink(link) {
  if (link.isButton) {
    return `
      <button class="mm-mobile-link" data-action="${escapeHtml(link.action)}" type="button">
        <span>${link.icon || ""}</span>
        <strong>${escapeHtml(link.label)}</strong>
      </button>
    `;
  }

  return `
    <a class="mm-mobile-link" href="${escapeHtml(link.href)}" aria-label="${escapeHtml(link.label)}">
      <span>${link.icon || ""}</span>
      <strong>${escapeHtml(link.label)}</strong>
    </a>
  `;
}

function renderBottomLink(link) {
  return `
    <a class="mm-bottom-link" href="${escapeHtml(link.href)}" aria-label="${escapeHtml(link.label)}">
      <span>${link.icon}</span>
      <small>${escapeHtml(link.label)}</small>
    </a>
  `;
}

function getLinksForRole() {
  if (!currentUser) {
    return [
      { label: "Marketplace", icon: "⌂", href: "products.html" },
      { label: "Login", icon: "↗", href: "login.html" },
      { label: "Join Now", icon: "+", href: "register.html" }
    ];
  }

  if (currentRole === "admin") {
    return [
      { label: "Admin", icon: "⚙", href: "dashboard.html" },
      { label: "Users", icon: "👥", href: "admin-users.html" },
      { label: "Products", icon: "□", href: "admin-products.html" },
      { label: "Payments", icon: "▣", href: "admin-payments.html" },
      { label: "Delivery", icon: "▸", href: "admin-delivery.html" },
      { label: "Analytics", icon: "⌁", href: "admin-analytics.html" },
      { label: "Marketplace", icon: "⌂", href: "products.html", desktop: false },
      { label: "Logout", icon: "×", isButton: true, action: "logout" }
    ];
  }

  if (currentRole === "seller") {
    return [
      { label: "Marketplace", icon: "⌂", href: "products.html" },
      { label: "Business", icon: "▣", href: "seller.html" },
      { label: "Orders", icon: "□", href: "seller-orders.html" },
      { label: "Earnings", icon: "₨", href: "seller-earnings.html" },
      { label: "Analytics", icon: "⌁", href: "seller-analytics.html" },
      { label: "Dashboard", icon: "○", href: "dashboard.html" },
      { label: "Logout", icon: "×", isButton: true, action: "logout" }
    ];
  }

  return [
    { label: "Marketplace", icon: "⌂", href: "products.html" },
    { label: "Wishlist", icon: "♡", href: "wishlist.html" },
    { label: "Orders", icon: "□", href: "my-orders.html" },
    { label: "My Account", icon: "○", href: "dashboard.html" },
    { label: "Cart", icon: "▣", href: "cart.html" },
    { label: "Logout", icon: "×", isButton: true, action: "logout", desktop: false }
  ];
}

function getBottomLinks() {
  if (currentRole === "admin") {
    return [
      { label: "Home", icon: "⌂", href: "index.html" },
      { label: "Admin", icon: "⚙", href: "admin.html" },
      { label: "Products", icon: "□", href: "admin-products.html" },
      { label: "Payments", icon: "▣", href: "admin-payments.html" },
      { label: "My Account", icon: "○", href: "dashboard.html" }
    ];
  }

  if (currentRole === "seller") {
    return [
      { label: "Home", icon: "⌂", href: "index.html" },
      { label: "Business", icon: "▣", href: "seller.html" },
      { label: "Orders", icon: "□", href: "seller-orders.html" },
      { label: "Market", icon: "◇", href: "products.html" },
      { label: "My Account", icon: "○", href: "dashboard.html" }
    ];
  }

  return [
    { label: "Home", icon: "⌂", href: "index.html" },
    { label: "Market", icon: "◇", href: "products.html" },
    { label: "Wishlist", icon: "♡", href: "wishlist.html" },
    { label: "Cart", icon: "▣", href: "cart.html" },
    { label: "My Account", icon: "○", href: currentUser ? "dashboard.html" : "login.html" }
  ];
}

function getUserBoxHtml() {
  if (!currentUser) {
    return `
      <strong>Welcome to MauMarket</strong>
      <span>Sign in or create an account to shop securely.</span>
    `;
  }

  const name =
    userData?.name ||
    userData?.fullName ||
    currentUser.displayName ||
    currentUser.email ||
    "MauMarket User";

  const roleLabel =
    currentRole === "admin"
      ? "Admin Account"
      : currentRole === "seller"
        ? "Merchant Account"
        : "Buyer Account";

  return `
    <strong>${escapeHtml(name)}</strong>
    <span>${roleLabel}</span>
  `;
}

function toggleMenu() {
  const sideMenu = document.getElementById("mmSideMenu");

  if (sideMenu?.classList.contains("show")) {
    closeMenu();
  } else {
    openMenu();
  }
}

function openMenu() {
  const sideMenu = document.getElementById("mmSideMenu");
  const overlay = document.getElementById("mmMenuOverlay");
  const button = document.getElementById("mmMenuBtn");

  if (!sideMenu || !overlay) return;

  sideMenu.inert = false;
  sideMenu.classList.add("show");
  sideMenu.setAttribute("aria-hidden", "false");

  overlay.classList.add("show");
  overlay.setAttribute("aria-hidden", "false");

  button?.classList.add("active");
  button?.setAttribute("aria-expanded", "true");

  document.body.classList.add("menu-open");

  requestAnimationFrame(() => {
    document.getElementById("mmMenuClose")?.focus();
  });
}

function closeMenu(options = {}) {
  const { restoreFocus = true } = options;

  const sideMenu = document.getElementById("mmSideMenu");
  const overlay = document.getElementById("mmMenuOverlay");
  const button = document.getElementById("mmMenuBtn");

  sideMenu?.classList.remove("show");
  sideMenu?.setAttribute("aria-hidden", "true");

  if (sideMenu) {
    sideMenu.inert = true;
  }

  overlay?.classList.remove("show");
  overlay?.setAttribute("aria-hidden", "true");

  button?.classList.remove("active");
  button?.setAttribute("aria-expanded", "false");

  document.body.classList.remove("menu-open");

  if (restoreFocus) {
    button?.focus();
  }
}


function runMobileNavSearch(scrollToResults) {
  const mobileInput = document.getElementById("mmMobileSearchInput");
  const desktopInput = document.getElementById("mmSearchInput");
  const category = document.getElementById("mmSearchCategory");

  const search = mobileInput?.value.trim() || "";
  const selectedCategory = category?.value || "";

  if (desktopInput && desktopInput.value !== search) {
    desktopInput.value = search;
  }

  if (isProductsPage()) {
    window.dispatchEvent(new CustomEvent("maumarket:search", {
      detail: {
        search,
        category: selectedCategory,
        scroll: scrollToResults
      }
    }));

    updateProductsUrl(search, selectedCategory);
    return;
  }

  const params = new URLSearchParams();

  if (search) params.set("search", search);
  if (selectedCategory) params.set("category", selectedCategory);

  window.location.href = params.toString()
    ? `products.html?${params.toString()}`
    : "products.html";
}


function runNavSearch(scrollToResults) {
  const input = document.getElementById("mmSearchInput");
  const category = document.getElementById("mmSearchCategory");

  const search = input?.value.trim() || "";
  const selectedCategory = category?.value || "";

  const mobileInput = document.getElementById("mmMobileSearchInput");
  if (mobileInput && mobileInput.value !== search) {
    mobileInput.value = search;
  }

  if (isProductsPage()) {
    window.dispatchEvent(new CustomEvent("maumarket:search", {
      detail: {
        search,
        category: selectedCategory,
        scroll: scrollToResults
      }
    }));

    updateProductsUrl(search, selectedCategory);
    return;
  }

  const params = new URLSearchParams();

  if (search) params.set("search", search);
  if (selectedCategory) params.set("category", selectedCategory);

  window.location.href = params.toString()
    ? `products.html?${params.toString()}`
    : "products.html";
}

function isProductsPage() {
  const path = window.location.pathname.toLowerCase();

  return path.endsWith("/products.html") ||
    path.endsWith("products.html") ||
    path.endsWith("/products") ||
    path === "/" && document.getElementById("productsGrid");
}

function updateProductsUrl(search, category) {
  const params = new URLSearchParams();

  if (search) params.set("search", search);
  if (category) params.set("category", category);

  const nextUrl = params.toString()
    ? `${window.location.pathname}?${params.toString()}`
    : window.location.pathname;

  window.history.replaceState({}, "", nextUrl);
}

async function logoutUser() {
  try {
    await signOut(auth);
    window.location.href = "login.html";
  } catch (error) {
    console.error("Logout failed:", error);

    alert(
      "You could not be signed out. Please check your connection and try again."
    );
  }
}

function markCurrentLinks() {
  const current = window.location.pathname.split("/").pop() || "index.html";

  document.querySelectorAll(".mm-desktop-links a, .mm-mobile-link, .mm-bottom-link").forEach((link) => {
    const href = link.getAttribute("href");

    if (!href) return;

    const file = href.split("?")[0];

    if (file === current) {
      link.classList.add("active");
    }
  });
}



async function updateCartBadge(event) {
  const badge = document.getElementById("mmCartBadge");
  if (!badge) return;

  /*
    MauMarket cart is stored in Firestore:
    carts/{uid}/items

    We do NOT use localStorage here anymore.
    This avoids fake cart numbers staying in the navbar.
  */
  localStorage.removeItem("cart");

  if (!currentUser) {
    setCartBadgeCount(0);
    return;
  }

  if (event?.detail?.count !== undefined) {
    setCartBadgeCount(Number(event.detail.count || 0));
    return;
  }

  try {
    const snapshot = await getDocs(
      collection(db, "carts", currentUser.uid, "items")
    );

    let count = 0;

    snapshot.forEach((docSnap) => {
      const item = docSnap.data();
      count += Number(item.quantity || 1);
    });

    setCartBadgeCount(count);
  } catch (error) {
    console.warn("Could not load the cart badge.");
    setCartBadgeCount(0);
  }
}

function setCartBadgeCount(count) {
  const badge = document.getElementById("mmCartBadge");
  if (!badge) return;

  const cleanCount = Number(count || 0);

  badge.textContent = cleanCount > 99 ? "99+" : String(cleanCount);
  badge.style.display = cleanCount > 0 ? "flex" : "none";

  if (cleanCount > 0) {
    badge.classList.remove("cart-bounce");
    void badge.offsetWidth;
    badge.classList.add("cart-bounce");
  }
}


window.addEventListener("maumarket:search", (event) => {
  const categorySelect = document.getElementById("mmSearchCategory");
  const category = event.detail?.category || "";

  if (!categorySelect) return;

  if (category) {
    ensureNavCategoryOption(category);
  }

  categorySelect.value = category;
});

window.addEventListener("cart-updated", updateCartBadge);
document.addEventListener("visibilitychange", () => {
  if (!document.hidden) updateCartBadge();
});

function getFriendlyNavigationError(error, fallbackMessage) {
  const code = String(error?.code || "");

  const messages = {
    "permission-denied":
      "You do not have permission to access this information.",
    "unavailable":
      "MauMarket is temporarily unavailable. Please try again.",
    "auth/network-request-failed":
      "Please check your internet connection and try again."
  };

  return messages[code] || fallbackMessage;
}

function escapeHtml(value) {
  return String(value || "")
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}
