import { auth, db, storage } from "./firebase-config.js";

import {
  onAuthStateChanged
} from "https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js";

import {
  doc,
  getDoc,
  setDoc,
  addDoc,
  collection,
  query,
  where,
  getDocs,
  deleteDoc,
  updateDoc,
  serverTimestamp
} from "https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js";

import {
  ref,
  uploadBytes,
  getDownloadURL
} from "https://www.gstatic.com/firebasejs/10.12.5/firebase-storage.js";

const COMMISSION_RATE = 0.10;

const shopName = document.getElementById("shopName");
const shopDescription = document.getElementById("shopDescription");
const shopPhone = document.getElementById("shopPhone");
const shopLocation = document.getElementById("shopLocation");
const shopLogo = document.getElementById("shopLogo");
const shopBanner = document.getElementById("shopBanner");
const saveShopBtn = document.getElementById("saveShopBtn");
const shopMessage = document.getElementById("shopMessage");

const shopSlug = document.getElementById("shopSlug");
const shopSlugStatus = document.getElementById("shopSlugStatus");
const shopSlugPrefix = document.getElementById("shopSlugPrefix");
const publicShopLink = document.getElementById("publicShopLink");
const copyShopLinkBtn = document.getElementById("copyShopLinkBtn");
const shareShopLinkBtn = document.getElementById("shareShopLinkBtn");
const shopLinkMessage = document.getElementById("shopLinkMessage");
const viewPublicShopBtn = document.getElementById("viewPublicShopBtn");
const sellerPublicShopItemsBtn = document.getElementById("sellerPublicShopItemsBtn");

const shopLogoPreview = document.getElementById("shopLogoPreview");
const shopBannerPreview = document.getElementById("shopBannerPreview");
const itemImagePreview = document.getElementById("itemImagePreview");

const slotInfo = document.getElementById("slotInfo");
const requestSlotsBtn = document.getElementById("requestSlotsBtn");
const slotMessage = document.getElementById("slotMessage");

const formTitle = document.getElementById("formTitle");
const itemType = document.getElementById("itemType");
const itemTitle = document.getElementById("itemTitle");
const itemDescription = document.getElementById("itemDescription");
const itemPrice = document.getElementById("itemPrice");
const itemStock = document.getElementById("itemStock");
const itemCategory = document.getElementById("itemCategory");
const serviceArea = document.getElementById("serviceArea");
const itemImage = document.getElementById("itemImage");
const saveItemBtn = document.getElementById("saveItemBtn");
const cancelEditBtn = document.getElementById("cancelEditBtn");
const itemMessage = document.getElementById("itemMessage");
const myItems = document.getElementById("myItems");

const sellerPricePreview = document.getElementById("sellerPricePreview");
const commissionPreview = document.getElementById("commissionPreview");
const buyerPricePreview = document.getElementById("buyerPricePreview");

let currentUser = null;
let currentUserData = null;
let currentShop = null;
let currentProductCount = 0;
let editingItemId = null;
let existingImageUrl = "";

let sellerCategories = [];

let slugCheckTimer = null;
let lastCheckedSlug = "";
let lastSlugAvailable = false;

onAuthStateChanged(auth, async (user) => {
  if (!user) {
    window.location.href = "login.html";
    return;
  }

  currentUser = user;

  const userSnap = await getDoc(doc(db, "users", user.uid));

  if (!userSnap.exists()) {
    window.location.href = "dashboard.html";
    return;
  }

  currentUserData = userSnap.data();

  if (
    currentUserData.role !== "seller" ||
    currentUserData.approved !== true ||
    currentUserData.blocked === true
  ) {
    window.location.href = "dashboard.html";
    return;
  }

  updatePricePreview();
  await loadShop();
  await loadSellerCategories();
  await loadMyItems();
});

itemPrice?.addEventListener("input", updatePricePreview);

shopName?.addEventListener("input", () => {
  if (!shopSlug) return;
  const currentValue = shopSlug.value.trim();
  if (!currentValue || shopSlug.dataset.autoGenerated === "true") {
    const generated = createShopSlug(shopName.value);
    shopSlug.value = generated;
    shopSlug.dataset.autoGenerated = "true";
    scheduleSlugAvailabilityCheck(generated);
    updatePublicShopLinkPreview(generated);
  }
});

shopSlug?.addEventListener("input", () => {
  const normalized = createShopSlug(shopSlug.value);
  shopSlug.value = normalized;
  shopSlug.dataset.autoGenerated = "false";
  scheduleSlugAvailabilityCheck(normalized);
  updatePublicShopLinkPreview(normalized);
});

copyShopLinkBtn?.addEventListener("click", copyPublicShopLink);
shareShopLinkBtn?.addEventListener("click", sharePublicShopLink);

shopLogo?.addEventListener("change", () => {
  previewSelectedImage(shopLogo.files?.[0], shopLogoPreview, "logo");
});
shopBanner?.addEventListener("change", () => {
  previewSelectedImage(shopBanner.files?.[0], shopBannerPreview, "banner");
});
itemImage?.addEventListener("change", () => {
  previewSelectedImage(itemImage.files?.[0], itemImagePreview, "item");
});


async function loadSellerCategories() {
  if (!itemCategory) return;

  itemCategory.disabled = true;
  itemCategory.innerHTML = `<option value="">Loading categories...</option>`;

  try {
    const snapshot = await getDocs(collection(db, "categories"));

    sellerCategories = [];

    snapshot.forEach((docSnap) => {
      const category = {
        id: docSnap.id,
        ...docSnap.data()
      };

      if (category.active !== false && category.name) {
        sellerCategories.push(category);
      }
    });

    sellerCategories.sort((a, b) => {
      const aOrder = Number(a.sortOrder || 0);
      const bOrder = Number(b.sortOrder || 0);

      if (aOrder !== bOrder) return aOrder - bOrder;

      return String(a.name || "").localeCompare(String(b.name || ""));
    });

    renderSellerCategoryOptions();
  } catch (error) {
    console.warn("Could not load seller categories:", error.message);
    sellerCategories = [{ name: "Other", sortOrder: 999 }];
    renderSellerCategoryOptions();
  }

  itemCategory.disabled = false;
}

function renderSellerCategoryOptions(selectedValue = "") {
  if (!itemCategory) return;

  itemCategory.innerHTML = `<option value="">Select a category</option>`;

  sellerCategories.forEach((category) => {
    const option = document.createElement("option");
    option.value = category.name;
    option.textContent = category.name;
    itemCategory.appendChild(option);
  });

  if (selectedValue) {
    ensureSellerCategoryOption(selectedValue);
    itemCategory.value = selectedValue;
  }
}

function ensureSellerCategoryOption(categoryName) {
  if (!itemCategory || !categoryName) return;

  const exists = Array.from(itemCategory.options).some(
    (option) => option.value === categoryName
  );

  if (!exists) {
    const option = document.createElement("option");
    option.value = categoryName;
    option.textContent = `${categoryName} (Existing category)`;
    itemCategory.appendChild(option);
  }
}


function createShopSlug(value) {
  return String(value || "")
    .toLowerCase()
    .trim()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/&/g, " and ")
    .replace(/['’]/g, "")
    .replace(/[^a-z0-9\s-]/g, "")
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 40);
}

function scheduleSlugAvailabilityCheck(value) {
  clearTimeout(slugCheckTimer);
  const slug = createShopSlug(value);
  updatePublicShopLinkPreview(slug);

  if (!slug) {
    lastCheckedSlug = "";
    lastSlugAvailable = false;
    updateSlugStatus("empty", "Not checked");
    setShopLinkControls(false);
    return;
  }

  updateSlugStatus("checking", "Checking...");
  slugCheckTimer = setTimeout(async () => {
    try {
      const available = await isShopSlugAvailable(slug, currentUser?.uid || "");
      lastCheckedSlug = slug;
      lastSlugAvailable = available;
      updateSlugStatus(available ? "available" : "unavailable", available ? "Available" : "Already taken");
      setShopLinkControls(available && currentShop?.slug === slug);
    } catch (error) {
      console.warn("Could not check shop slug:", error.message);
      updateSlugStatus("error", "Check failed");
    }
  }, 450);
}

async function isShopSlugAvailable(slug, currentSellerId) {
  if (!slug) return false;
  const slugQuery = query(collection(db, "shops"), where("slug", "==", slug));
  const snapshot = await getDocs(slugQuery);
  if (snapshot.empty) return true;
  return snapshot.docs.every((shopDoc) => {
    const data = shopDoc.data();
    const ownerId = data.ownerId || data.sellerId || shopDoc.id;
    return shopDoc.id === currentSellerId || ownerId === currentSellerId;
  });
}

function updateSlugStatus(state, text) {
  if (!shopSlugStatus) return;
  shopSlugStatus.className = `shop-slug-status ${state}`;
  shopSlugStatus.textContent = text;
}

function getProjectBaseUrl() {
  const currentUrl = new URL(window.location.href);
  const pathParts = currentUrl.pathname.split("/");
  pathParts.pop();
  const basePath = `${pathParts.join("/")}/`;
  return `${currentUrl.origin}${basePath}`;
}

function buildPublicShopUrl(slug) {
  const normalizedSlug = createShopSlug(slug);
  if (!normalizedSlug) return "";
  return `${getProjectBaseUrl()}shop.html?shop=${encodeURIComponent(normalizedSlug)}`;
}

function updatePublicShopLinkPreview(slug) {
  const publicUrl = buildPublicShopUrl(slug);
  if (shopSlugPrefix) shopSlugPrefix.textContent = "shop.html?shop=";
  if (publicShopLink) publicShopLink.value = publicUrl;
  const isSavedSlug = Boolean(currentShop?.slug) && currentShop.slug === createShopSlug(slug);
  setShopLinkControls(isSavedSlug);
}

function updatePublicShopButtons(slug) {
  const publicUrl = buildPublicShopUrl(slug);
  const canOpen = Boolean(publicUrl);
  if (viewPublicShopBtn) {
    viewPublicShopBtn.href = publicUrl || "#";
    viewPublicShopBtn.style.display = canOpen ? "inline-flex" : "none";
  }
  if (sellerPublicShopItemsBtn) {
    sellerPublicShopItemsBtn.href = publicUrl || "#";
    sellerPublicShopItemsBtn.style.display = canOpen ? "inline-flex" : "none";
  }
  setShopLinkControls(canOpen);
}

function setShopLinkControls(enabled) {
  const hasLink = Boolean(publicShopLink?.value);
  const canUse = Boolean(enabled && hasLink);
  if (copyShopLinkBtn) copyShopLinkBtn.disabled = !canUse;
  if (shareShopLinkBtn) shareShopLinkBtn.disabled = !canUse;
}

async function copyPublicShopLink() {
  const link = publicShopLink?.value || "";
  if (!link) return;
  try {
    await navigator.clipboard.writeText(link);
    if (copyShopLinkBtn) {
      const originalText = copyShopLinkBtn.textContent;
      copyShopLinkBtn.textContent = "Copied!";
      setTimeout(() => { copyShopLinkBtn.textContent = originalText || "Copy Link"; }, 1600);
    }
    if (shopLinkMessage) shopLinkMessage.textContent = "Public shop link copied to your clipboard.";
  } catch (error) {
    if (shopLinkMessage) shopLinkMessage.textContent = "Copy failed. Select the link and copy it manually.";
  }
}

async function sharePublicShopLink() {
  const link = publicShopLink?.value || "";
  if (!link) return;
  const shareData = {
    title: `${shopName?.value.trim() || "MauMarket Shop"} | MauMarket`,
    text: `Visit ${shopName?.value.trim() || "my shop"} on MauMarket.`,
    url: link
  };
  try {
    if (navigator.share) {
      await navigator.share(shareData);
      if (shopLinkMessage) shopLinkMessage.textContent = "Shop link shared successfully.";
      return;
    }
    await navigator.clipboard.writeText(link);
    if (shopLinkMessage) shopLinkMessage.textContent = "Sharing is not supported here, so the link was copied instead.";
  } catch (error) {
    if (error?.name === "AbortError") return;
    if (shopLinkMessage) shopLinkMessage.textContent = "The shop link could not be shared.";
  }
}

function previewSelectedImage(file, previewElement, type) {
  if (!file || !previewElement) return;
  if (!file.type.startsWith("image/")) {
    previewElement.style.display = "none";
    return;
  }
  const reader = new FileReader();
  reader.onload = () => renderImagePreview(previewElement, reader.result, "Selected image preview", type);
  reader.readAsDataURL(file);
}

function renderImagePreview(previewElement, imageUrl, altText, type = "item") {
  if (!previewElement || !imageUrl) return;
  previewElement.innerHTML = `
    <img src="${escapeHtml(imageUrl)}" alt="${escapeHtml(altText)}" class="seller-preview-image seller-preview-${escapeHtml(type)}">
  `;
  previewElement.style.display = "block";
}

async function uploadImage(file, folder) {
  const safeName = file.name.replaceAll(" ", "-");
  const fileName = `${Date.now()}-${safeName}`;
  const imageRef = ref(storage, `${folder}/${currentUser.uid}/${fileName}`);
  await uploadBytes(imageRef, file);
  return await getDownloadURL(imageRef);
}

function calculatePrices(rawPrice) {
  const sellerPrice = roundMoney(Number(rawPrice || 0));
  const commissionAmount = roundMoney(sellerPrice * COMMISSION_RATE);
  const buyerPrice = roundMoney(sellerPrice + commissionAmount);

  return {
    sellerPrice,
    commissionRate: COMMISSION_RATE,
    commissionPercent: 10,
    commissionAmount,
    buyerPrice
  };
}

function updatePricePreview() {
  const prices = calculatePrices(itemPrice?.value || 0);

  if (sellerPricePreview) {
    sellerPricePreview.textContent = formatRs(prices.sellerPrice);
  }

  if (commissionPreview) {
    commissionPreview.textContent = formatRs(prices.commissionAmount);
  }

  if (buyerPricePreview) {
    buyerPricePreview.textContent = formatRs(prices.buyerPrice);
  }
}

async function loadShop() {
  const shopSnap = await getDoc(doc(db, "shops", currentUser.uid));

  if (!shopSnap.exists()) {
    currentShop = null;
    const generatedSlug = createShopSlug(shopName?.value || "");
    if (shopSlug && generatedSlug) {
      shopSlug.value = generatedSlug;
      shopSlug.dataset.autoGenerated = "true";
      updatePublicShopLinkPreview(generatedSlug);
    }
    setShopLinkControls(false);
    return;
  }

  currentShop = { id: shopSnap.id, ...shopSnap.data() };
  if (shopName) shopName.value = currentShop.shopName || "";
  if (shopDescription) shopDescription.value = currentShop.description || "";
  if (shopPhone) shopPhone.value = currentShop.phone || "";
  if (shopLocation) shopLocation.value = currentShop.location || "";

  const existingSlug = currentShop.slug || createShopSlug(currentShop.shopName || "");
  if (shopSlug) {
    shopSlug.value = existingSlug;
    shopSlug.dataset.autoGenerated = currentShop.slug ? "false" : "true";
  }

  lastCheckedSlug = existingSlug;
  lastSlugAvailable = Boolean(existingSlug);
  updateSlugStatus(existingSlug ? "available" : "empty", existingSlug ? "Current link" : "Not set");
  updatePublicShopLinkPreview(existingSlug);
  updatePublicShopButtons(existingSlug);

  if (currentShop.logoUrl) {
    renderImagePreview(shopLogoPreview, currentShop.logoUrl, "Current shop logo", "logo");
  }
  if (currentShop.bannerUrl) {
    renderImagePreview(shopBannerPreview, currentShop.bannerUrl, "Current shop banner", "banner");
  }
}

saveShopBtn?.addEventListener("click", async () => {
  if (!currentUser) return;

  const normalizedShopName = shopName?.value.trim() || "";
  const normalizedSlug = createShopSlug(shopSlug?.value || normalizedShopName);

  if (!normalizedShopName) {
    shopMessage.textContent = "Shop name is required.";
    return;
  }
  if (!normalizedSlug) {
    shopMessage.textContent = "Please enter a valid personalized shop link.";
    return;
  }
  if (normalizedSlug.length < 3) {
    shopMessage.textContent = "Your personalized shop link must contain at least 3 characters.";
    return;
  }

  saveShopBtn.disabled = true;
  shopMessage.textContent = "Checking shop link...";

  try {
    const available = await isShopSlugAvailable(normalizedSlug, currentUser.uid);
    if (!available) {
      updateSlugStatus("unavailable", "Already taken");
      shopMessage.textContent = "This personalized shop link is already used by another seller.";
      return;
    }

    updateSlugStatus("available", "Available");
    shopMessage.textContent = "Saving shop...";

    let logoUrl = currentShop?.logoUrl || "";
    let bannerUrl = currentShop?.bannerUrl || "";

    if (shopLogo?.files?.[0]) logoUrl = await uploadImage(shopLogo.files[0], "shops");
    if (shopBanner?.files?.[0]) bannerUrl = await uploadImage(shopBanner.files[0], "shops");

    const shopData = {
      ownerId: currentUser.uid,
      sellerId: currentUser.uid,
      shopName: normalizedShopName,
      slug: normalizedSlug,
      description: shopDescription?.value.trim() || "",
      phone: shopPhone?.value.trim() || "",
      location: shopLocation?.value.trim() || "",
      logoUrl,
      bannerUrl,
      active: true,
      approved: true,
      updatedAt: serverTimestamp()
    };

    if (!currentShop?.createdAt) shopData.createdAt = serverTimestamp();

    await setDoc(doc(db, "shops", currentUser.uid), shopData, { merge: true });

    if (shopSlug) {
      shopSlug.value = normalizedSlug;
      shopSlug.dataset.autoGenerated = "false";
    }

    lastCheckedSlug = normalizedSlug;
    lastSlugAvailable = true;
    shopMessage.textContent = "Shop saved successfully.";
    if (shopLinkMessage) shopLinkMessage.textContent = "Your public shop link is ready to share.";
    await loadShop();
  } catch (error) {
    console.error("Could not save shop:", error);
    shopMessage.textContent = error.message || "The shop could not be saved.";
  } finally {
    saveShopBtn.disabled = false;
  }
});

saveItemBtn?.addEventListener("click", async () => {
  if (!currentUser) return;

  const enteredSellerPrice = Number(itemPrice.value || 0);

  if (!itemTitle.value.trim() || enteredSellerPrice <= 0) {
    itemMessage.textContent = "Title and seller price are required.";
    return;
  }

  if (!itemCategory.value) {
    itemMessage.textContent = "Please select a category.";
    return;
  }

  const productLimit = Number(currentUserData.productLimit || 50);

  if (!editingItemId && currentProductCount >= productLimit) {
    itemMessage.textContent = "You reached your product slot limit. Request more slots.";
    return;
  }

  saveItemBtn.disabled = true;
  itemMessage.textContent = editingItemId ? "Updating item..." : "Adding item...";

  try {
    let imageUrl = existingImageUrl;

    if (itemImage.files[0]) {
      imageUrl = await uploadImage(itemImage.files[0], "products");
    }

    const prices = calculatePrices(enteredSellerPrice);

    const itemData = {
      sellerId: currentUser.uid,
      shopId: currentUser.uid,
      shopName: currentShop?.shopName || shopName?.value.trim() || "MauMarket Seller",
      shopSlug: currentShop?.slug || createShopSlug(shopSlug?.value || shopName?.value || ""),
      type: itemType.value,
      title: itemTitle.value.trim(),
      description: itemDescription.value.trim(),

      sellerPrice: prices.sellerPrice,
      commissionRate: prices.commissionRate,
      commissionPercent: prices.commissionPercent,
      commissionAmount: prices.commissionAmount,
      buyerPrice: prices.buyerPrice,

      // Keep this for older marketplace/product/cart pages.
      // Buyer-facing price is stored here.
      price: prices.buyerPrice,

      stock: Number(itemStock.value || 0),
      category: itemCategory.value,
      serviceArea: serviceArea.value.trim(),
      imageUrl,
      updatedAt: serverTimestamp()
    };

    if (editingItemId) {
      await updateDoc(doc(db, "products", editingItemId), itemData);
      itemMessage.textContent = "Item updated successfully.";
    } else {
      await addDoc(collection(db, "products"), {
        ...itemData,
        active: true,
        createdAt: serverTimestamp()
      });

      itemMessage.textContent = "Item added successfully.";
    }

    resetItemForm();
    await loadMyItems();
  } catch (error) {
    itemMessage.textContent = error.message;
  }

  saveItemBtn.disabled = false;
});

cancelEditBtn?.addEventListener("click", resetItemForm);

function resetItemForm() {
  editingItemId = null;
  existingImageUrl = "";

  formTitle.textContent = "Add Product / Service";
  saveItemBtn.textContent = "Add Item";
  cancelEditBtn.style.display = "none";

  itemType.value = "product";
  itemTitle.value = "";
  itemDescription.value = "";
  itemPrice.value = "";
  itemStock.value = "";
  itemCategory.value = "";
  serviceArea.value = "";
  itemImage.value = "";

  if (itemImagePreview) {
    itemImagePreview.innerHTML = "";
    itemImagePreview.style.display = "none";
  }

  updatePricePreview();
}

async function loadMyItems() {
  myItems.innerHTML = "Loading...";

  const q = query(
    collection(db, "products"),
    where("sellerId", "==", currentUser.uid)
  );

  const snapshot = await getDocs(q);

  currentProductCount = snapshot.size;
  const productLimit = Number(currentUserData.productLimit || 50);

  if (slotInfo) {
    slotInfo.textContent = `You are using ${currentProductCount} / ${productLimit} product slots.`;
  }

  if (snapshot.empty) {
    myItems.innerHTML = "<p>No items added yet.</p>";
    return;
  }

  myItems.innerHTML = "";

  snapshot.forEach((docSnap) => {
    const item = docSnap.data();

    const sellerPrice = getSellerPrice(item);
    const buyerPrice = Number(item.buyerPrice || item.price || 0);
    const commissionAmount = Number(item.commissionAmount || Math.max(0, buyerPrice - sellerPrice));

    const div = document.createElement("div");
    div.className = "card product-card";

    div.innerHTML = `
      ${item.imageUrl ? `<img src="${escapeHtml(item.imageUrl)}" alt="${escapeHtml(item.title)}">` : ""}
      <span class="badge">${escapeHtml(item.type || "item")}</span>
      <span class="status-badge ${item.active ? "active" : "hidden"}">
        ${item.active ? "Visible" : "Hidden"}
      </span>

      <h3>${escapeHtml(item.title || "Untitled")}</h3>
      <p>${escapeHtml(item.category || "Other")}</p>

      <div class="seller-price-breakdown">
        <p><strong>Seller receives:</strong> ${formatRs(sellerPrice)}</p>
        <p><strong>MauMarket 10%:</strong> ${formatRs(commissionAmount)}</p>
        <p><strong>Buyer sees:</strong> ${formatRs(buyerPrice)}</p>
      </div>

      <div class="seller-actions">
        <button class="edit-btn">Edit</button>
        <button class="toggle-btn">${item.active ? "Hide" : "Show"}</button>
        <button class="danger-btn">Delete</button>
      </div>
    `;

    div.querySelector(".edit-btn").addEventListener("click", () => {
      editingItemId = docSnap.id;
      existingImageUrl = item.imageUrl || "";

      if (existingImageUrl) {
        renderImagePreview(itemImagePreview, existingImageUrl, item.title || "Current listing image", "item");
      }

      formTitle.textContent = "Edit Product / Service";
      saveItemBtn.textContent = "Update Item";
      cancelEditBtn.style.display = "inline-block";

      itemType.value = item.type || "product";
      itemTitle.value = item.title || "";
      itemDescription.value = item.description || "";
      itemPrice.value = getSellerPrice(item);
      itemStock.value = item.stock || "";
      const existingCategory = item.category || "";
      ensureSellerCategoryOption(existingCategory);
      itemCategory.value = existingCategory;
      serviceArea.value = item.serviceArea || "";

      updatePricePreview();

      window.scrollTo({ top: 0, behavior: "smooth" });
    });

    div.querySelector(".toggle-btn").addEventListener("click", async () => {
      await updateDoc(doc(db, "products", docSnap.id), {
        active: !item.active,
        updatedAt: serverTimestamp()
      });

      await loadMyItems();
    });

    div.querySelector(".danger-btn").addEventListener("click", async () => {
      if (!confirm("Delete this item permanently?")) return;

      await deleteDoc(doc(db, "products", docSnap.id));
      await loadMyItems();
    });

    myItems.appendChild(div);
  });
}

if (requestSlotsBtn) {
  requestSlotsBtn.addEventListener("click", async () => {
    if (!currentUser) return;

    const requestedAmount = prompt("How many extra slots do you want? Example: 50");

    if (!requestedAmount || Number(requestedAmount) <= 0) {
      slotMessage.textContent = "Invalid slot request.";
      return;
    }

    await addDoc(collection(db, "quotaRequests"), {
      sellerId: currentUser.uid,
      sellerName: currentUserData.name || "",
      sellerEmail: currentUserData.email || "",
      currentLimit: Number(currentUserData.productLimit || 50),
      requestedExtra: Number(requestedAmount),
      status: "pending",
      createdAt: serverTimestamp()
    });

    slotMessage.textContent = "Request sent to admin.";
  });
}

function getSellerPrice(item) {
  if (item.sellerPrice !== undefined && item.sellerPrice !== null) {
    return Number(item.sellerPrice || 0);
  }

  const buyerPrice = Number(item.buyerPrice || item.price || 0);

  if (buyerPrice <= 0) return 0;

  return roundMoney(buyerPrice / 1.1);
}

function roundMoney(value) {
  return Math.round(Number(value || 0) * 100) / 100;
}

function formatRs(value) {
  return `Rs ${Number(value || 0).toLocaleString("en-US", {
    minimumFractionDigits: 0,
    maximumFractionDigits: 2
  })}`;
}

function escapeHtml(value) {
  return String(value || "")
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}
